In [1]:
import numpy as np

In [2]:
a = np.random.normal(size=(10, 1))
b = np.random.normal(size=(1, 10))

In [4]:
a

array([[ 0.29621728],
       [ 0.9880077 ],
       [-1.31668752],
       [ 0.56741443],
       [ 0.45660853],
       [ 0.01831206],
       [ 2.32980003],
       [ 0.75711759],
       [ 1.62282643],
       [ 1.63063887]])

In [5]:
b

array([[ 0.4126144 , -1.69647769,  0.45853356,  0.84207443, -1.660322  ,
        -0.68425768,  0.8556869 ,  0.92217086,  0.64986287,  1.20707598]])

In [6]:
np.dot(a, b)

array([[ 0.12222351, -0.502526  ,  0.13582556,  0.24943699, -0.49181606,
        -0.20268895,  0.25346924,  0.27316294,  0.19250061,  0.35755676],
       [ 0.4076662 , -1.67613302,  0.45303468,  0.83197601, -1.64041091,
        -0.67605186,  0.84542524,  0.91111191,  0.64206952,  1.19260036],
       [-0.54328423,  2.233731  , -0.60374541, -1.10874889,  2.18612525,
         0.90095355, -1.12667226, -1.21421086, -0.85566632, -1.58934187],
       [ 0.23412336, -0.96260593,  0.26017856,  0.47780518, -0.94209066,
        -0.38825768,  0.4855291 ,  0.52325306,  0.36874157,  0.68491233],
       [ 0.18840325, -0.77462618,  0.20937033,  0.38449836, -0.75811718,
        -0.31243789,  0.39071393,  0.42107108,  0.29673293,  0.55116118],
       [ 0.00755582, -0.03106601,  0.0083967 ,  0.01542012, -0.03040392,
        -0.01253017,  0.01566939,  0.01688685,  0.01190033,  0.02210405],
       [ 0.96130904, -3.95245378,  1.0682915 ,  1.96186503, -3.86821825,
        -1.59418357,  1.99357937,  2.14847371

In [3]:
result = np.dot(a, b)
result.shape

(10, 10)

In [7]:
aLength = np.linalg.norm( a )
bLength = np.linalg.norm( b )

In [8]:
aLength

3.823885417110984

In [9]:
bLength

3.2641171273455383

In [11]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])